### PR TITLE
Update to Rust nightly

### PR DESCRIPTION
**Pull request by tamird**
@alexcrichton see https://github.com/rust-lang/rust/issues/23374 for the `unmarked_api` bit

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks!

**Comment by tamird** [comment]
@alexcrichton there's still a failing test there - probably to do with upstream changes to `path`

**Comment by tamird** [comment]
(said failing test is also present on master)

**Comment by alexcrichton** [comment]
I [fixed up the test](https://github.com/rust-lang/glob/commit/46d35f8246ea476b9f9e1f25fb65798bdbc98908) in an extra commit

**Comment by tamird** [comment]
Great, thanks!

**Pull request merged**
