### PR TITLE
Add support for windows verbatim disk paths

### PR DESCRIPTION
**Pull request by nico-abram**
Fixes https://github.com/rust-lang-nursery/glob/issues/111

### CODE REVIEW

**Comment by nico-abram** [comment]
Replaced matches! with an if-let. CI runs on an old rustc and I don't know what glob's MSRV policy is.

**Comment by swiftcoder** [comment]
Pulled this patch locally and confirmed it addresses the issue observed in getzola/zola#1932.

Happy to help out, should an extra pair of hands be needed to merge and release.

**Comment by JohnTitor** [comment]
Seems you disabled access to this branch, could you rebase to trigger the latest CI?

**Comment by nico-abram** [comment]
Rebased.

Edits by maintainers seems to be enabled:
imagen

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
> Edits by maintainers seems to be enabled

Hmm, that's weird, maybe I force-pushed for rebasing and that's a culprit.

Anyway, this LGTM, thank you for the PR and sorry for the long delay!

**Comment by Wumpf** [comment]
Just ran into the exact same issue fixed here after hunting down why a buildscript didn't behave properly on Windows.
Any chance this could get into a bug-fix release any time soon? :)

**Pull request merged**
